"""
Complete list of all pages on https://design-system.service.gov.uk/
Generated by deep-scanning the site's sitemap page.
"""

BASE = "https://design-system.service.gov.uk"

# Every page on the site, organised by section
PAGES = {
    # ── Root / standalone pages ──────────────────────────────────────
    "root": [
        f"{BASE}/",
        f"{BASE}/sitemap/",
        f"{BASE}/cookies/",
        f"{BASE}/accessibility-statement/",
        f"{BASE}/privacy-policy/",
        f"{BASE}/contact/",
        f"{BASE}/design-system-team/",
    ],

    # ── Get started ──────────────────────────────────────────────────
    "get-started": [
        f"{BASE}/get-started/",
        f"{BASE}/get-started/prototyping/",
        f"{BASE}/get-started/production/",
        f"{BASE}/get-started/labels-legends-headings/",
        f"{BASE}/get-started/extending-and-modifying-components/",
        f"{BASE}/get-started/focus-states/",
        f"{BASE}/get-started/new-type-scale/",
    ],

    # ── Styles ───────────────────────────────────────────────────────
    "styles": [
        f"{BASE}/styles/",
        # Page structure
        f"{BASE}/styles/page-template/",
        f"{BASE}/styles/layout/",
        f"{BASE}/styles/spacing/",
        f"{BASE}/styles/section-break/",
        # Typography
        f"{BASE}/styles/typeface/",
        f"{BASE}/styles/type-scale/",
        f"{BASE}/styles/headings/",
        f"{BASE}/styles/paragraphs/",
        f"{BASE}/styles/links/",
        f"{BASE}/styles/lists/",
        f"{BASE}/styles/font-override-classes/",
        # Visual elements
        f"{BASE}/styles/colour/",
        f"{BASE}/styles/images/",
    ],

    # ── Components ───────────────────────────────────────────────────
    "components": [
        f"{BASE}/components/",
        f"{BASE}/components/accordion/",
        f"{BASE}/components/back-link/",
        f"{BASE}/components/breadcrumbs/",
        f"{BASE}/components/button/",
        f"{BASE}/components/character-count/",
        f"{BASE}/components/checkboxes/",
        f"{BASE}/components/cookie-banner/",
        f"{BASE}/components/date-input/",
        f"{BASE}/components/details/",
        f"{BASE}/components/error-message/",
        f"{BASE}/components/error-summary/",
        f"{BASE}/components/exit-this-page/",
        f"{BASE}/components/fieldset/",
        f"{BASE}/components/file-upload/",
        f"{BASE}/components/footer/",
        f"{BASE}/components/header/",
        f"{BASE}/components/inset-text/",
        f"{BASE}/components/notification-banner/",
        f"{BASE}/components/pagination/",
        f"{BASE}/components/panel/",
        f"{BASE}/components/password-input/",
        f"{BASE}/components/phase-banner/",
        f"{BASE}/components/radios/",
        f"{BASE}/components/select/",
        f"{BASE}/components/service-navigation/",
        f"{BASE}/components/skip-link/",
        f"{BASE}/components/summary-list/",
        f"{BASE}/components/table/",
        f"{BASE}/components/tabs/",
        f"{BASE}/components/tag/",
        f"{BASE}/components/task-list/",
        f"{BASE}/components/text-input/",
        f"{BASE}/components/textarea/",
        f"{BASE}/components/warning-text/",
    ],

    # ── Patterns ─────────────────────────────────────────────────────
    "patterns": [
        f"{BASE}/patterns/",
        # Ask users for…
        f"{BASE}/patterns/addresses/",
        f"{BASE}/patterns/bank-details/",
        f"{BASE}/patterns/dates/",
        f"{BASE}/patterns/email-addresses/",
        f"{BASE}/patterns/equality-information/",
        f"{BASE}/patterns/names/",
        f"{BASE}/patterns/national-insurance-numbers/",
        f"{BASE}/patterns/passwords/",
        f"{BASE}/patterns/payment-card-details/",
        f"{BASE}/patterns/phone-numbers/",
        # Help users to…
        f"{BASE}/patterns/check-a-service-is-suitable/",
        f"{BASE}/patterns/check-answers/",
        f"{BASE}/patterns/complete-multiple-tasks/",
        f"{BASE}/patterns/confirm-a-phone-number/",
        f"{BASE}/patterns/confirm-an-email-address/",
        f"{BASE}/patterns/contact-a-department-or-service-team/",
        f"{BASE}/patterns/create-a-username/",
        f"{BASE}/patterns/create-accounts/",
        f"{BASE}/patterns/exit-a-page-quickly/",
        f"{BASE}/patterns/navigate-a-service/",
        f"{BASE}/patterns/start-using-a-service/",
        f"{BASE}/patterns/validation/",
        # Pages
        f"{BASE}/patterns/confirmation-pages/",
        f"{BASE}/patterns/cookies-page/",
        f"{BASE}/patterns/page-not-found-pages/",
        f"{BASE}/patterns/problem-with-the-service-pages/",
        f"{BASE}/patterns/question-pages/",
        f"{BASE}/patterns/service-unavailable-pages/",
        f"{BASE}/patterns/step-by-step-navigation/",
    ],

    # ── Community ────────────────────────────────────────────────────
    "community": [
        f"{BASE}/community/",
        # What we're working on
        f"{BASE}/community/upcoming-components-patterns/",
        f"{BASE}/community/roadmap/",
        f"{BASE}/community/whats-new/",
        # Ways to get involved
        f"{BASE}/community/continuous-research/",
        f"{BASE}/community/share-research-findings/",
        f"{BASE}/community/propose-a-component-or-pattern/",
        f"{BASE}/community/develop-a-component-or-pattern/",
        f"{BASE}/community/propose-a-content-change-using-github/",
        # How we work
        f"{BASE}/community/community-principles/",
        f"{BASE}/community/contribution-criteria/",
        f"{BASE}/community/design-system-working-group/",
        f"{BASE}/community/blogs-talks-podcasts/",
        # Resources
        f"{BASE}/community/resources-and-tools/",
        # Events and workshops
        f"{BASE}/community/design-system-day/",
        f"{BASE}/community/code-of-conduct/",
    ],

    # ── Accessibility ────────────────────────────────────────────────
    "accessibility": [
        f"{BASE}/accessibility/",
        f"{BASE}/accessibility/accessibility-strategy/",
    ],
}


def all_pages() -> list[str]:
    """Return a flat list of every page URL."""
    return [url for urls in PAGES.values() for url in urls]


if __name__ == "__main__":
    pages = all_pages()
    print(f"Total pages found: {len(pages)}\n")

    for section, urls in PAGES.items():
        print(f"-- {section} ({len(urls)} pages) --")
        for url in urls:
            path = url.replace(BASE, "") or "/"
            print(f"  {path}")
        print()
